apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: apm-server
  name: apm-server
spec:
  ports:
    - name: "8200"
      port: 8200
      targetPort: 8200
    - name: "6060"
      port: 6060
      targetPort: 6060
  selector:
    io.kompose.service: apm-server
