apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/spring-petclinic-spring-petclinic-net: "true"
        io.kompose.service: elasticsearch
    spec:
      containers:
        - env:
            - name: ELASTIC_PASSWORD
              value: changeme
            - name: ES_JAVA_OPTS
              value: -Xms2048m -Xmx2048m
            - name: bootstrap.memory_lock
              value: "true"
            - name: cluster.name
              value: sa-demo-spring-petclinic
            - name: discovery.type
              value: single-node
            - name: http.host
              value: 0.0.0.0
            - name: node.name
              value: petclinic-elasticsearch
            - name: xpack.ml.node_concurrent_job_allocations
              value: "8"
            - name: xpack.monitoring.enabled
              value: "true"
            - name: xpack.security.enabled
              value: "true"
          image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
          livenessProbe:
            exec:
              command:
                - curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
            failureThreshold: 10
            periodSeconds: 20
          name: spring-petclinic-elasticsearch
          ports:
            - containerPort: 9200
              hostIP: 127.0.0.1
              hostPort: 9200
              protocol: TCP
          resources:
            limits:
              memory: "4294967296"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: esdata01
      restartPolicy: Always
      volumes:
        - name: esdata01
          persistentVolumeClaim:
            claimName: esdata01
