apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibana
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/spring-petclinic-spring-petclinic-net: "true"
        io.kompose.service: kibana
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: ELASTICSEARCH_PASSWORD
              value: changeme
            - name: ELASTICSEARCH_USERNAME
              value: elastic
            - name: SERVER_HOST
              value: 0.0.0.0
            - name: XPACK_MONITORING_ENABLED
              value: "true"
            - name: XPACK_MONITORING_KIBANA_COLLECTION_ENABLED
              value: "false"
            - name: XPACK_SECURITY_SECURECOOKIES
              value: "false"
          image: docker.elastic.co/kibana/kibana:7.4.0
          livenessProbe:
            exec:
              command:
                - curl
                - --write-out
                - '''HTTP %{http_code}'''
                - --silent
                - --output
                - /dev/null
                - http://kibana:5601/
            failureThreshold: 10
            periodSeconds: 10
          name: spring-petclinic-kibana
          ports:
            - containerPort: 5601
              hostIP: 127.0.0.1
              hostPort: 5601
              protocol: TCP
      restartPolicy: Always
