apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: spring-client-loadgen
  name: spring-client-loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spring-client-loadgen
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/spring-petclinic-spring-petclinic-net: "true"
        io.kompose.service: spring-client-loadgen
    spec:
      containers:
        - env:
            - name: PETCLINIC_BASE_URL
              value: http://spring-petclinic-client:3000
          image: spring-client-loadgen:7.4.0
          name: spring-client-loadgen
      restartPolicy: Always
