apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: spring-server-loadgen
  name: spring-server-loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spring-server-loadgen
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/spring-petclinic-spring-petclinic-net: "true"
        io.kompose.service: spring-server-loadgen
    spec:
      containers:
        - env:
            - name: DATA_FILES
              value: /opt/data_files
            - name: ENDPOINT_BASE
              value: spring-petclinic-client
            - name: ENDPOINT_PORT
              value: "3000"
            - name: ENDPOINT_PROTOCOL
              value: http
          image: spring-server-loadgen:7.4.0
          name: spring-server-loadgen
      restartPolicy: Always
